package OWP_GlobsDb.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '33f9b299-dff2-4339-8ad9-317c6c3e2c7e' (id = 'OWP_GlobsDb_Build')
accordingly, and delete the patch script.
*/
changeBuildType("33f9b299-dff2-4339-8ad9-317c6c3e2c7e") {
    expectSteps {
        gradle {
            tasks = "buildDependents"
            incremental = true
            useGradleWrapper = true
            enableStacktrace = true
            coverageEngine = idea {
                includeClasses = "org.globsframework.*"
            }
            dockerImage = "gradle:4.3.1"
            dockerRunParameters = "--net=host"
        }
        gradle {
            tasks = "publish"
            useGradleWrapper = true
            enableStacktrace = true
            dockerImage = "gradle:4.3.1"
            dockerRunParameters = "--net=host"
        }
    }
    steps {
        insert(1) {
            script {
                name = "Fossa"
                scriptContent = """
                    ./gradlew build -x test
                    fossa
                    fossa test
                """.trimIndent()
                dockerImage = "gradle:4.3.1"
                dockerRunParameters = """
                    -v /usr/local/bin/fossa:/usr/local/bin/fossa
                    -e FOSSA_API_KEY=9009fadc3b7be531316376a3d5f3cd87
                """.trimIndent()
            }
        }
    }
}
